### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by halvardssm** [libdns/route53#7]
Hi! I am trying to use Certmagic with DynamoDB as store and route53 as provider, but I am encountering the error below. This error only occurs if the domain does not already exist in the DynamoDB store. After some digging (and with my limited expertise with Go) I narrowed it down to it being a problem with the aws-sdk or with a reference in the route53 provider. Have you encountered something like this before? Have I overlooked anything in the configuration? 

Thank you in advance!

```txt
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa35e3a]

goroutine 1 [running]:
github.com/aws/aws-sdk-go/service/route53.(*Route53).newRequest(0x0, 0xc00034b680, 0xd83fa0, 0xc0002fc2a0, 0xdce060, 0xc0002bf180, 0x0)
/root/go/pkg/mod/github.com/aws/aws-sdk-go@v1.30.29/service/route53/service.go:90 +0x3a
github.com/aws/aws-sdk-go/service/route53.(*Route53).ListHostedZonesByNameRequest(0x0, 0xc0002fc2a0, 0x20, 0xdd84e0)
/root/go/pkg/mod/github.com/aws/aws-sdk-go@v1.30.29/service/route53/api.go:4208 +0xdb
github.com/aws/aws-sdk-go/service/route53.(*Route53).ListHostedZonesByNameWithContext(0x0, 0xfa1300, 0xc0000380f0, 0xc0002fc2a0, 0x0, 0x0, 0x0, 0xd96420, 0xc000248240, 0x1fd
a78)
/root/go/pkg/mod/github.com/aws/aws-sdk-go@v1.30.29/service/route53/api.go:4294 +0x39
github.com/libdns/route53.(*Provider).getZoneID(0xc00028a840, 0xfa1300, 0xc0000380f0, 0xc0002a3ba0, 0x10, 0x417005, 0x7fdd534bcc18, 0x18, 0x100)
/root/go/pkg/mod/github.com/libdns/route53@v1.1.1/client.go:102 +0x11c
github.com/libdns/route53.(*Provider).AppendRecords(0xc00028a840, 0xfa1300, 0xc0000380f0, 0xc0002a3ba0, 0x10, 0xc0002bf130, 0x1, 0x1, 0x0, 0xc00075e600, ...)
/root/go/pkg/mod/github.com/libdns/route53@v1.1.1/provider.go:37 +0x77
github.com/caddyserver/certmagic.(*DNS01Solver).Present(0xc00007b630, 0xfa1300, 0xc0000380f0, 0xc0002a3b18, 0x6, 0xc00031a1e0, 0x45, 0xc0002a3b20, 0x7, 0x0, ...)
/root/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1/solvers.go:292 +0x506
github.com/caddyserver/certmagic.solverWrapper.Present(0xf97860, 0xc00007b630, 0xfa1300, 0xc0000380f0, 0xc0002a3b18, 0x6, 0xc00031a1e0, 0x45, 0xc0002a3b20, 0x7, ...)
/root/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1/solvers.go:661 +0x196
github.com/mholt/acmez.(*Client).presentForNextChallenge(0xc00000f720, 0xfa1300, 0xc0000380f0, 0xc000094820, 0x5, 0xc00034a240)
/root/go/pkg/mod/github.com/mholt/acmez@v0.1.3/client.go:393 +0x995
github.com/mholt/acmez.(*Client).solveChallenges(0xc00000f720, 0xfa1300, 0xc0000380f0, 0xc000038450, 0x5, 0xc00034a240, 0x1, 0x4, 0x1, 0x0, ...)
/root/go/pkg/mod/github.com/mholt/acmez@v0.1.3/client.go:344 +0x287
github.com/mholt/acmez.(*Client).ObtainCertificateUsingCSR(0xc00000f720, 0xfa1300, 0xc0000380f0, 0xc000038450, 0x5, 0xc00034a240, 0x1, 0x4, 0x1, 0x0, ...)
/root/go/pkg/mod/github.com/mholt/acmez@v0.1.3/client.go:127 +0x48b
github.com/caddyserver/certmagic.(*ACMEManager).doIssue(0xc0001ec600, 0xfa1300, 0xc0000380f0, 0xc0000a8900, 0x0, 0xc0001ec600, 0x1, 0x0, 0x0)
/root/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1/acmemanager.go:315 +0x1b3
github.com/caddyserver/certmagic.(*ACMEManager).Issue(0xc0001ec600, 0xfa1300, 0xc0000380f0, 0xc0000a8900, 0x1, 0x1, 0xc0000a8901)
/root/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1/acmemanager.go:244 +0xd6
github.com/caddyserver/certmagic.(*Config).obtainCert.func2(0xfa1300, 0xc0000380f0, 0xfa9580, 0xc00007b5e0)
/root/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1/config.go:523 +0x45b
github.com/caddyserver/certmagic.(*Config).obtainCert(0xc000267860, 0xfa1300, 0xc0000380f0, 0xc000039eb0, 0xf, 0x1, 0x0, 0x0)
/root/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1/config.go:570 +0x3a9
github.com/caddyserver/certmagic.(*Config).ObtainCertSync(...)
/root/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1/config.go:421
github.com/caddyserver/certmagic.(*Config).manageOne.func1(0xdd92e0, 0xc00044d800)
/root/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1/config.go:334 +0x3ff
github.com/caddyserver/certmagic.(*Config).manageOne(0xc000267860, 0xfa1300, 0xc0000380f0, 0xc000039eb0, 0xf, 0x0, 0x1, 0xfa9501)
/root/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1/config.go:361 +0x27b
github.com/caddyserver/certmagic.(*Config).manageAll(0xc000267860, 0xfa1300, 0xc0000380f0, 0xc00011ded8, 0x2, 0x2, 0x0, 0x1, 0x11)
/root/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1/config.go:312 +0x1f1
github.com/caddyserver/certmagic.(*Config).ManageSync(...)
/root/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1/config.go:251
github.com/caddyserver/certmagic.TLS(0xc00011fed8, 0x2, 0x2, 0x1, 0x1, 0xc000035f20)
/root/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1/certmagic.go:181 +0x98
main.main()
```

Here is a minimum example of the code I am using:

```go
import (
	"fmt"
	"github.com/caddyserver/certmagic"
	"github.com/libdns/route53"
	dynamodbstore "github.com/silinternational/certmagic-storage-dynamodb/v2"
)

	certmagic.Default.Storage = &dynamodbstore.Storage{
		Table:     "certs",
		AwsRegion: "eu-west-1",
	}

	certmagic.DefaultACME.Agreed = true
	certmagic.DefaultACME.Email = "some@email.com"

	certmagic.DefaultACME.DNS01Solver = &certmagic.DNS01Solver{
		DNSProvider: &route53.Provider{},
	}

	config, err := certmagic.TLS([]string{
		domain,
		fmt.Sprintf("*.%s", domain),
	})
```

**Comment by israel-ramos** [comment]
Same issue here! 
The stack trace points to the line number 90 at [https://github.com/aws/aws-sdk-go/blob/main/service/route53/service.go](url)
